export const KeyWords = [
    { value: 'Android', label: 'Android' },
    { value: 'Art', label: 'Art' },
    { value: 'Astronomy', label: 'Astronomy'},
    { value: 'Austen', label: 'Austen'},
    { value: 'Baseball', label: 'Baseball'},
    { value: 'Basketball', label: 'Basketball'},
    { value: 'Bhagat', label: 'Bhagat'},
    { value: 'Biography', label: 'Biography'},
    { value: 'Brief', label: 'Brief'},
    { value: 'Business', label: 'Business'},
    { value: 'Camus', label: 'Camus'},
    { value: 'Cervantes', label: 'Cervantes'},
    { value: 'Christie', label: 'Christie'},
    { value: 'Classics', label: 'Classics'},
    { value: 'Comics', label: 'Comics'},
    { value: 'Cook', label: 'Cook'},
    { value: 'Cricket', label: 'Cricket'},
    { value: 'Cycling', label: 'Cycling'},
    { value: 'Desai', label: 'Desai'},
    { value: 'Design', label: 'Design'},
    { value: 'Development', label: 'Development'},
    { value: 'Digital Marketing', label: 'Digital Marketing'},
    { value: 'Drama', label: 'Drama'},
    { value: 'Drawing', label: 'Drawing'},
    { value: 'Dumas', label: 'Dumas'},
    { value: 'Education', label: 'Education'},
    { value: 'Everything', label: 'Everything'},
    { value: 'Fantasy', label: 'Fantasy'},
    { value: 'Film', label: 'Film'},
    { value: 'Finance', label: 'Finance'},
    { value: 'First', label: 'First'},
    { value: 'Fitness', label: 'Fitness'},
    { value: 'Football', label: 'Football'},
    { value: 'Future', label: 'Future'},
    { value: 'Games', label: 'Games'},
    { value: 'Gandhi', label: 'Gandhi'},
    { value: 'Homer', label: 'Homer'},
    { value: 'Horror', label: 'Horror'},
    { value: 'Ibsen', label: 'Ibsen'},
    { value: 'Journey', label: 'Journey'},
    { value: 'Kafka', label: 'Kafka'},
    { value: 'King', label: 'King'},
    { value: 'Lahiri', label: 'Lahiri'},
    { value: 'Larsson', label: 'Larsson'},
    { value: 'Learn', label: 'Learn'},
    { value: 'Literary Fiction', label: 'Literary Fiction'},
    { value: 'Make', label: 'Make'},
    { value: 'Manage', label: 'Manage'},
    { value: 'Marquez', label: 'Marquez'},
    { value: 'Money', label: 'Money'},
    { value: 'Mystery', label: 'Mystery'},
    { value: 'Negotiate', label: 'Negotiate'},
    { value: 'Painting', label: 'Painting'},
    { value: 'Philosophy', label: 'Philosophy'},
    { value: 'Photography', label: 'Photography'},
    { value: 'Poetry', label: 'Poetry'},
    { value: 'Production', label: 'Production'},
    { value: 'Programming', label: 'Programming'},
    { value: 'React', label: 'React'},
    { value: 'Redux', label: 'Redux'},
    { value: 'River', label: 'River'},
    { value: 'Robotics', label: 'Robotics'},
    { value: 'Rowling', label: 'Rowling'},
    { value: 'Satire', label: 'Satire'},
    { value: 'Science Fiction', label: 'Science Fiction'},
    { value: 'Shakespeare', label: 'Shakespeare'},
    { value: 'Singh', label: 'Singh'},
    { value: 'Swimming', label: 'Swimming'},
    { value: 'Tale', label: 'Tale'},
    { value: 'Thrun', label: 'Thrun'},
    { value: 'Time', label: 'Time'},
    { value: 'Tolstoy', label: 'Tolstoy'},
    { value: 'Travel', label: 'Travel'},
    { value: 'Ultimate', label: 'Ultimate'},
    { value: 'Virtual Reality', label: 'Virtual Reality'},
    { value: 'Web Development', label: 'Web Development'},
    { value: 'iOS', label: 'iOS'}
  ];